#!/bin/bash

for DIRNAME in data src notebooks results tests doc
do
    mkdir $DIRNAME
done

touch src/__init__.py
touch tests/__init__.py
touch README.md
echo "This is a project template for generic data science and/or machine"\
    "learning projects. The setup_dir.sh script also initializes a local"\
    "git repository. The contents of data and results directories are"\
    "added to the .gitignore file. Data does not need to be version"\
    "controlled and the results directory should only contain files that"\
    "are automatically generated by src or notebooks files." >> README.md

git init
touch .gitignore
echo "data/*" >> .gitignore
echo "results/*" >> .gitignore
